In [14]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [15]:
import keras

from __future__ import print_function
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from time import time
#np.random.seed(1337)  # for reproducibility

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import Convolution1D, MaxPooling1D
from keras.utils import np_utils
from keras.callbacks import TensorBoard


# set parameters:
test_dim = 499
maxlen = 100
nb_filter = 256
filter_length_1 = 10
filter_length_2 = 5
hidden_dims = 750
nb_epoch = 12
nb_classes = 4
split_ratio = 0.15

print('Loading data...')

# X = np.load('/content/drive/My Drive/Colab Notebooks/data/numpy_vectors/x_test_mfcc_500_50:50_samples_sliced_out.npy')
# y = np.load('/content/drive/My Drive/Colab Notebooks/data/numpy_vectors/y_label_500_50:50_samples_sliced_out.npy')
X = np.load('/content/drive/My Drive/Colab Notebooks/data/numpy_vectors/x_all_accents_trim.npy')
y = np.load('/content/drive/My Drive/Colab Notebooks/data/numpy_vectors/y_all_accents_trim.npy')
print(X.shape)
print(y.shape)

Loading data...
(6183, 499, 13)
(6183,)


In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=split_ratio)
Y_train = keras.utils.to_categorical(y_train, nb_classes)
Y_test = keras.utils.to_categorical(y_test, nb_classes)
# print(Y_test)
# print(Y_train)

In [17]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D
from keras.layers import Activation, Dropout, Flatten, Dense
nb_train_samples = X.shape
input_shape = (test_dim, 13)
for batch_size in range(25, 26, 5):
    print('Build model...')
    model = Sequential()

    model = Sequential()
    model.add(Conv1D(32, (3), input_shape=input_shape))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size=(2)))

    model.add(Conv1D(32, (3)))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size=(2)))

    model.add(Conv1D(64, (3)))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size=(2)))

    model.add(Flatten())
    model.add(Dense(64))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(4))
    model.add(Activation('sigmoid'))
    model.add(Dense(nb_classes, activation='softmax'))

    model.compile(loss='categorical_crossentropy',
                  optimizer='rmsprop',
                  metrics=['accuracy'])
   
    model.fit(X_train, Y_train, steps_per_epoch=nb_train_samples[0] // batch_size,
            nb_epoch=5, shuffle='true', verbose=1)

    Y_preds = model.predict(X_test)
    for i in range(len(Y_preds)):
        print(Y_preds[i], Y_test[i])
    score = model.evaluate(X_test, Y_test, verbose=1)
    print(score)

Build model...


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:37: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.


Epoch 1/5
247/247 [==============================] - 68s 273ms/step - loss: 0.9186 - acc: 0.8232
Epoch 2/5
247/247 [==============================] - 66s 269ms/step - loss: 0.5926 - acc: 0.9608
Epoch 3/5
247/247 [==============================] - 66s 268ms/step - loss: 0.4210 - acc: 0.9837
Epoch 4/5
247/247 [==============================] - 66s 268ms/step - loss: 0.2998 - acc: 0.9943
Epoch 5/5
247/247 [==============================] - 66s 269ms/step - loss: 0.2126 - acc: 0.9960
[0.9500202  0.0205347  0.00364142 0.02580367] [1. 0. 0. 0.]
[0.9500202  0.02053472 0.00364143 0.02580367] [1. 0. 0. 0.]
[0.01610085 0.14193833 0.8349755  0.00698531] [0. 0. 1. 0.]
[0.9500202  0.0205347  0.00364142 0.02580367] [1. 0. 0. 0.]
[0.01610085 0.14193833 0.8349755  0.00698531] [0. 0. 1. 0.]
[0.10063472 0.6841923  0.15561461 0.05955834] [0. 1. 0. 0.]
[0.01610085 0.14193833 0.8349755  0.00698531] [0. 0. 1. 0.]
[0.10063472 0.6841923  0.15561461 0.05955834] [0. 1. 0. 0.]
[0.05864213 0.03495739 0.00697748 0