In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
import keras

from __future__ import print_function
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from time import time
#np.random.seed(1337)  # for reproducibility

from keras.preprocessing import sequence
from keras.models import Sequential
from keras.layers.core import Dense, Dropout, Activation, Flatten
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import Convolution1D, MaxPooling1D
from keras.utils import np_utils
from keras.callbacks import TensorBoard


# set parameters:
test_dim = 499
maxlen = 100
nb_filter = 256
filter_length_1 = 10
filter_length_2 = 5
hidden_dims = 750
nb_epoch = 12
nb_classes = 4
split_ratio = 0.15

print('Loading data...')

# X = np.load('/content/drive/My Drive/Colab Notebooks/data/numpy_vectors/x_test_mfcc_500_50:50_samples_sliced_out.npy')
# y = np.load('/content/drive/My Drive/Colab Notebooks/data/numpy_vectors/y_label_500_50:50_samples_sliced_out.npy')
X = np.load('/content/drive/My Drive/Colab Notebooks/data/numpy_vectors/x_all_accents_trim.npy')
y = np.load('/content/drive/My Drive/Colab Notebooks/data/numpy_vectors/y_all_accents_trim.npy')
print(X.shape)
print(y.shape)

Using TensorFlow backend.


Loading data...
(6183, 499, 13)
(6183,)


In [0]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=split_ratio)
Y_train = keras.utils.to_categorical(y_train, nb_classes)
Y_test = keras.utils.to_categorical(y_test, nb_classes)
# print(Y_test)
# print(Y_train)

In [4]:
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Sequential
from keras.layers import Conv1D, MaxPooling1D
from keras.layers import Activation, Dropout, Flatten, Dense
nb_train_samples = X.shape
input_shape = (test_dim, 13)
for batch_size in range(25, 26, 5):
    print('Build model...')
    model = Sequential()

    model = Sequential()
    model.add(Conv1D(32, (3), input_shape=input_shape))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size=(2)))

    model.add(Conv1D(32, (3)))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size=(2)))

    model.add(Conv1D(64, (3)))
    model.add(Activation('relu'))
    model.add(MaxPooling1D(pool_size=(2)))

    model.add(Flatten())
    model.add(Dense(64))
    model.add(Activation('relu'))
    model.add(Dropout(0.5))
    model.add(Dense(4))
    model.add(Activation('sigmoid'))
    model.add(Dense(nb_classes, activation='softmax'))

    model.compile(loss='categorical_crossentropy',
                  optimizer='rmsprop',
                  metrics=['accuracy'])
   
    model.fit(X_train, Y_train, steps_per_epoch=nb_train_samples[0] // batch_size,
            nb_epoch=5, shuffle='true', verbose=1)

    Y_preds = model.predict(X_test)
    for i in range(len(Y_preds)):
        print(Y_preds[i], Y_test[i])
    score = model.evaluate(X_test, Y_test, verbose=1)
    print(score)

Build model...





Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:37: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.





Epoch 1/5





247/247 [==============================] - 73s 296ms/step - loss: 0.8350 - acc: 0.8018
Epoch 2/5
247/247 [==============================] - 65s 264ms/step - loss: 0.5257 - acc: 0.8690
Epoch 3/5
247/247 [==============================] - 65s 263ms/step - loss: 0.3627 - acc: 0.8735
Epoch 4/5
247/247 [==============================] - 65s 262ms/step - loss: 0.2592 - acc: 0.9170
Epoch 5/5
247/247 [==============================] - 65s 262ms/step - loss: 0.1913 - acc: 0.9945
[0.88993895 0.00809983 0.01394933 0.08801191] [1. 0. 0. 0.]
[0.00918496 0.04146634 0.9398193  0.00952939] [0. 0. 1. 0.]
[0.88993895 0.00809983 0.01394933 0.08801191] [1. 0. 0. 0.]
[0.00516971 0.9456235  0.03874563 0.01046126] [0. 1. 0. 0.]
[0.32772088 0.0714123  0.07102291 0.52984387] [0. 0. 0. 1.]
[0.88993895 0.00809983 0.01394933 0.08801191] [1. 0. 0. 0.]
[0.88993895 0.00809983 0.01394933 0.08801191] [1. 0. 0. 0.]
[0.00918496 0.04146634 0.9398193  0.00952939] [0. 0. 1. 0.]
[0.00918496 0.04146634 0.93